# Generated by Django 5.0.6 on 2025-10-14 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barbiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("specialita", models.CharField(max_length=200)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="barbieri/"),
                ),
                ("attivo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Barbieri",
            },
        ),
        migrations.CreateModel(
            name="Servizio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField()),
                (
                    "durata_minuti",
                    models.IntegerField(help_text="Durata del servizio in minuti"),
                ),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "verbose_name_plural": "Servizi",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome completo"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                ("data_registrazione", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clienti",
            },
        ),
        migrations.CreateModel(
            name="Appuntamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ora", models.DateTimeField(verbose_name="Data e ora")),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("confermato", "Confermato"),
                            ("completato", "Completato"),
                            ("cancellato", "Cancellato"),
                            ("in_attesa", "In Attesa"),
                        ],
                        default="confermato",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("modificato_il", models.DateTimeField(auto_now=True)),
                (
                    "barbiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appuntamenti",
                        to="appointments.barbiere",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appuntamenti",
                        to="appointments.cliente",
                    ),
                ),
                (
                    "servizio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.servizio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Appuntamenti",
                "ordering": ["-data_ora"],
            },
        ),
    ]
