# Generated by Django 5.2.7 on 2025-10-21 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[\\d\\s\\-\\(\\)]+$",
                        "Inserisci un numero di telefono valido (es. +39 123 456 7890 o 0123456789)",
                    )
                ],
            ),
        ),
    ]
